### ISSUE TITLE
namespace annotations for profile enforcement

### ISSUE THREAD

**Issue by mblaschke** [softonic/node-policy-webhook#10]
it should be possible to set the profile annotation on namespace level which should enforce a profile and ignore the pod profile (or make it possible to configure enforcement or default profile)

example:
```
apiVersion: v1
kind: Namespace
metadata:
  name: foobar
  annotations:
    # for default profile (can be overwritten in pod)
    nodepolicy.softonic.io/default-profile: "stateless"
   # for enforced (not overwritable profile)
    nodepolicy.softonic.io/enforce-profile: "stateless"
```
